.TH KMESS 1 "Nov 2005" "K Desktop Environment" "MSN messenger for KDE"
.SH NAME
kmess
- MSN messenger for KDE
.SH SYNOPSIS
kmess [Qt-options] [KDE-options] [options]
.SH DESCRIPTION
Kmess is a MSN messenger for the K Desktop Environment. It supports only
the MSN protocol and has a nice design.

.SH OPTIONS
.SS Arguments:
.TP
.B --autologin
Autologin with the given email address
.SS

.SS Generic options:
.TP
.B  --help                                                
Show help about options
.TP
.B  --help-qt
Show Qt specific options
.TP
.B  --help-kde                
Show KDE specific options
.TP  
.B  --help-all
Show all options
.TP
.B  --author                  
Show author information
.TP
.B  -v, --version             
Show version information
.TP
.B  --license
Show license information
.SS

.SS Qt options:
.TP
.B  --display <displayname>   
Use the X-server display 'displayname'
.TP
.B  --session <sessionId>
Restore the application for the given 'sessionId'
.TP
.B  --cmap        
Causes the application to install a private color map on an 8-bit display
.TP
.B  --ncols <count>           
Limits the number of colors allocated in the color cube on an 8-bit display,
if the application is using the QApplication::ManyColor color specification
.TP
.B  --nograb
Tells Qt to never grab the mouse or the keyboard
.TP
.B  --dograb
Running under a debugger can cause an implicit --nograb, use --dograb 
to override
.TP  
.B  --sync
Switches to synchronous mode for debugging
.TP
.B  --fn, --font <fontname>
Defines the application font
.TP
.B  --bg, --background <color>
Sets the default background color and an application palette (light 
and dark shades are calculated)
.TP
.B  --fg, --foreground <color>
Dets the default foreground color
.TP
.B  --btn, --button <color>
Sets the default button color
.TP
.B  --name <name>             
Sets the application name
.TP
.B  --title <title>
Sets the application title (caption)
.TP
.B  --visual TrueColor
Forces the application to use a TrueColor visual on an 8-bit display
.TP
.B  --inputstyle <inputstyle> 
Sets XIM (X Input Method) input style. Possible values are onthespot,
overthespot, offthespot and root
.TP
.B  --im <XIM server>         
Set XIM server
.TP
.B  --noxim                   
Disable XIM
.TP
.B  --reverse            
Mirrors the whole layout of widgets
.SS

.SS KDE options:
.TP
.B  --caption <caption>
Use 'caption' as name in the titlebar
.TP
.B  --icon <icon>
Use 'icon' as the application icon
.TP
.B  --miniicon <icon>
Use 'icon' as the icon in the titlebar
.TP
.B  --config <filename>
Use alternative configuration file
.TP
.B  --dcopserver <server>
Use the DCOP Server specified by 'server'
.TP
.B  --nocrashhandler   
Disable crash handler, to get core dumps
.TP 
.B  --waitforwm
Waits for a WM_NET compatible windowmanager
.TP
.B  --style <style>           
Sets the application GUI style
.TP
.B  --geometry <geometry>     
Sets the client geometry of the main widget - see man X for the argument format
.SS 

.SH SEE ALSO
/usr/share/doc/kmess/README
.br
.SH AUTHORS
.nf
Mario Iseli <admin@marioiseli.com>

